/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace std;
/* Header for class com_example_romio_opencvtest_NativeCpp */

#ifndef _Included_com_example_romio_opencvtest_NativeCpp
#define _Included_com_example_romio_opencvtest_NativeCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_romio_opencvtest_NativeCpp
 * Method:    convert2Grey
 * Signature: (JJ)I
 */


JNIEXPORT jint JNICALL Java_com_example_romio_opencvtest_NativeCpp_convert2Grey
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_example_romio_opencvtest_NativeCpp_detectRed
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
